### ISSUE TITLE
Getting locked stacks and isolated GPU instances

### ISSUE THREAD

**Issue by raphaeltm** [defang-io/defang#166] opened 2024-03-06 22:44 UTC
I'm still running into issues with `defang compose down` when using GPU instances.

I can't remember if down failed loudly or silently, but I think it failed silently because I only realized a week later that my GPU instance was still running, which leads me to assume that it looked to me like `down` worked.

That being said, it is possible that I ran it and turned off my machine... which is another argument to have a simple list of CD task executions per project with statuses related to them. I think that's my top priority feature at the moment, along with BYOD for domains hosted elsewhere than AWS.

I think this is still related to the Capacity Provider / ASG issue, but I'm not completely sure.

**Comment by lionello** [comment] 2024-03-06 23:12
duplicate of #124

**Closed by lionello** 2024-03-06 23:12 UTC

**Comment by lionello** [comment] 2024-03-25 18:15
More info, in case this happens again https://repost.aws/knowledge-center/ecs-tasks-stop-delayed-draining
